import os
from typing import Any


ROBOFLOW_CLIENT: Any = None


def get_roboflow_client() -> Any:
    global ROBOFLOW_CLIENT
    if ROBOFLOW_CLIENT is None:
        api_key = os.getenv("ROBOFLOW_API_KEY")
        if not api_key:
            raise RuntimeError("ROBOFLOW_API_KEY is not configured")
        from inference_sdk import InferenceHTTPClient

        ROBOFLOW_CLIENT = InferenceHTTPClient.init(
            api_url=os.getenv("ROBOFLOW_API_URL", "https://serverless.roboflow.com"),
            api_key=api_key,
        )
    return ROBOFLOW_CLIENT


def compact_scenarios(value: Any) -> list[str]:
    if not isinstance(value, list):
        raise ValueError("scenarios must be a non-empty list generated by the AI planner")

    scenarios = []
    seen = set()
    for item in value:
        label = " ".join(str(item or "").replace("\n", " ").split()).strip()
        key = label.lower()
        if label and key not in seen:
            scenarios.append(label[:80])
            seen.add(key)

    if not scenarios:
        raise ValueError("scenarios must be a non-empty list generated by the AI planner")
    return scenarios[:16]
